from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "scripts" / "workhub_delivery_app.py"


def assert_contains(path: Path, needle: str) -> None:
    text = path.read_text(encoding="utf-8")
    assert needle in text, f"Expected {path.relative_to(ROOT)} to contain {needle!r}"


def main() -> None:
    package_path = ROOT / "package.json"
    css_input = ROOT / "src" / "workhub.css"
    static_css = ROOT / "static" / "workhub.css"

    assert package_path.exists(), "package.json is required for the Tailwind/daisyUI build"
    package = json.loads(package_path.read_text(encoding="utf-8"))
    assert package["scripts"]["build:css"] == "tailwindcss -i ./src/workhub.css -o ./static/workhub.css --minify"
    assert package["devDependencies"]["daisyui"].startswith("^5.")
    assert "@tailwindcss/cli" in package["devDependencies"]
    assert "tailwindcss" in package["devDependencies"]

    assert css_input.exists(), "src/workhub.css is required"
    assert_contains(css_input, '@import "tailwindcss";')
    assert_contains(css_input, '@plugin "daisyui"')
    assert_contains(css_input, '@source "../scripts/workhub_delivery_app.py";')

    assert static_css.exists(), "static/workhub.css must be generated by npm run build:css"
    assert static_css.stat().st_size > 1000, "Generated CSS looks too small"

    assert_contains(APP, 'STATIC_DIR = ROOT / "static"')
    assert_contains(APP, 'self.path.startswith("/static/")')
    assert_contains(APP, '<link rel="stylesheet" href="/static/workhub.css" />')


if __name__ == "__main__":
    main()
